# data_dir defines the directory of the embedded DB.
data_dir = ""
# listen_addr defines the JSON API listening address in the form of host:port.
listen_addr = ""
# seeds defines a list of initial seed nodes.
seeds = []
# ipstack_key defines the ipstack API access key required for geolocation queries.
ipstack_key = ""
# reseed_size defines the size of the reseed list for which to reseed the node
# pool after its been exhausted. It is populated by the crawling process.
reseed_size = 100
# crawl_interval defines the interval in which to retrigger a crawl after the
# node pool is exhausted.
crawl_interval = 15
